# -*- coding: utf-8 -*-
"""Preprocessing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZJDvhKeNEwQKPE00liCQPyxz9a6nbkvM
"""

from sklearn import datasets
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

data = pd.read_csv("kyphosis.csv")
data.head(20)
#vertebrae
#Age in month
#number of vertebrae
#first starting topmost vertebrae



data.mean()

data.describe()

data.isnull().sum()

print(data.to_string())

x=data['Kyphosis']
y=data["Age"]
plt.bar(x,y,label="Age",color="green")
plt.xlabel("Kyphosis")
plt.ylabel("Patient Age")
plt.title("Patient Information")
plt.legend()
plt.show()

sns.countplot(data['Kyphosis'])

plt.boxplot(data["Age"])

plt.figure(figsize = (15,15))
sns.countplot(data['Age'])

from sklearn.preprocessing import LabelEncoder

l = LabelEncoder()
l.fit_transform(data['Kyphosis'])

out = data.clip(data.quantile(0.2), data.quantile(0.8), axis = 1)
print(out)
plt.boxplot(out)
plt.show()

data['Kyphosis']=data['Kyphosis'].map({'absent': 0, 'present':1})

data['Kyphosis']

sns.heatmap(data.corr(), annot = True)

data.isnull().sum()



data['Age'].clip(data['Age'].quantile(0.2), data['Age'].quantile(0.8), inplace = True)
data['Start'].clip(data['Start'].quantile(0.2), data['Start'].quantile(0.8), inplace = True)
data['Number'].clip(data['Number'].quantile(0.2), data['Number'].quantile(0.8), inplace = True)



plt.boxplot(data['Age'])

plt.boxplot(data['Number'])

plt.boxplot(data['Start'])

