# -*- coding: utf-8 -*-
"""Hardcode_feature_scalling.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BKyXf1z7C6rQdikPu410gOHIhNJE5W8R
"""

from sklearn import datasets
import numpy as np
import pandas as pd

wine = datasets.load_wine()
data = wine.data
data

data1 = pd.DataFrame(data,columns = wine.feature_names)
data1

x = (data1 - np.mean(data1))/np.std(data1)
x

def standardize(dataFrame):
  mean_value = dataFrame.mean()
  std_dev = dataFrame.std()
  standard = (dataFrame - mean_value) / std_dev
  return standardize

data1_standardized = standardize(data1)
# data1.head()

# data1_standardized.head()

# from sklearn import MinMaxScaler
minimum = np.min(data1)

maximum = np.max(data1)

y = (data1 - minimum) / (maximum - minimum)
y

average = np.mean(data1)
average

z = (data1 - average) / (maximum - minimum)
z

# import sklearn.preprocessing import StandardScaler
# scaler = StandardScaler()

